# ---
# - name: Configure PostgreSQL
#   hosts: database_servers
#   become: yes

#   tasks:
#     - name: Install PostgreSQL
#       apt:
#         name: postgresql
#         state: present
#       register: postgresql_installed

#     - name: Ensure PostgreSQL is running
#       service:
#         name: postgresql
#         state: started
#       when: postgresql_installed.changed

#     - name: Configure PostgreSQL to listen on all interfaces
#       community.general.postgresql_conf:
#         name: listen_addresses
#         value: '*'
#         restart: yes

#   handlers:
#     - name: restart postgresql
#       service:
#         name: postgresql
#         state: restarted


---
- name: Configure PostgreSQL to listen on all interfaces
  hosts: dbservers
  become: yes

  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
      register: postgresql_installed

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
      when: postgresql_installed.changed

    - name: Configure PostgreSQL to listen on all interfaces
      lineinfile:
        path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
        regexp: '^#listen_addresses ='
        line: "listen_addresses = '*'"
        state: present
      notify: restart postgresql

  handlers:
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted



        - name: Allow password authentication in pg_hba.conf
      community.postgresql.postgresql_pg_hba:
        database: all
        user: all
        address: all
        method: md5
      notify: reload postgresql  

    - name: create database
      community.postgresql.postgresql_db:
        name: "{{db_name}}"
        owner: "{{db_user}}"
        state: present

    - name: create database user
      community.postgresql.postgresql_user:
        db: "{{ db_name }}"
        user: "{{db_user}}"
        password: "{{db_password}}"
        priv: "*.*:ALL"
        state: present
        encrypted: yes         